Repository Kueen-never-cry/sb03-findex-team1, pull requests merged in 2025-06, with the labels that each got.

#35 Feat/지수 차트 조회
  src/main/java/com/kueennevercry/findex/config/Config.java
  src/main/java/com/kueennevercry/findex/config/OpenApiProperties.java
  src/main/java/com/kueennevercry/findex/config/ReseTemplateConfig.java
  src/main/java/com/kueennevercry/findex/controller/Contoller.java
  src/main/java/com/kueennevercry/findex/controller/IndexDataController.java
  src/main/java/com/kueennevercry/findex/dto/ChartPoint.java
  src/main/java/com/kueennevercry/findex/dto/Dto.java
  src/main/java/com/kueennevercry/findex/dto/PeriodType.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexDataSyncRequest.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexChartResponse.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexDataResponse.java
  src/main/java/com/kueennevercry/findex/entity/Entity.java
  src/main/java/com/kueennevercry/findex/entity/IndexData.java
  src/main/java/com/kueennevercry/findex/infra/openapi/DefaultOpenApiClient.java
  src/main/java/com/kueennevercry/findex/infra/openapi/OpenApiClient.java
  src/main/java/com/kueennevercry/findex/service/IndexDataService.java
  src/main/java/com/kueennevercry/findex/service/IndexDataServiceImpl.java
  src/main/java/com/kueennevercry/findex/service/Service.java
  src/main/resources/application.yaml
  src/test/resources/http/index-data-chart.http
Labels: Settings, Test, New Feature

#36 Feat/지수 정보 조회 GET API 엔드포인트 구현
  src/main/java/com/kueennevercry/findex/controller/IndexInfoController.java
  src/main/java/com/kueennevercry/findex/dto/IndexInfoDto.java
  src/main/java/com/kueennevercry/findex/entity/IndexInfo.java
  src/main/java/com/kueennevercry/findex/repository/IndexInfoRepository.java
  src/main/java/com/kueennevercry/findex/repository/Repository.java
  src/main/java/com/kueennevercry/findex/service/IndexInfoService.java
  src/test/resources/http/index-data-chart.http
Labels: Test, New Feature

#41 Feature/지수 데이터 목록 조회
  src/main/java/com/kueennevercry/findex/controller/IndexDataController.java
  src/main/java/com/kueennevercry/findex/dto/IndexDataDto.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexDataCreateDto.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexDataUpdateDto.java
  src/main/java/com/kueennevercry/findex/entity/IndexData.java
  src/main/java/com/kueennevercry/findex/entity/IndexInfo.java
  src/main/java/com/kueennevercry/findex/entity/SourceType.java
  src/main/java/com/kueennevercry/findex/mapper/IndexDataMapper.java
  src/main/java/com/kueennevercry/findex/mapper/IndexInfoMapper.java
  src/main/java/com/kueennevercry/findex/mapper/Mapper.java
  src/main/java/com/kueennevercry/findex/repository/IndexDataRepository.java
  src/main/java/com/kueennevercry/findex/service/IndexDataService.java
  src/main/java/com/kueennevercry/findex/service/IndexDataServiceImpl.java
  src/main/resources/db.yaml
  src/main/resources/schema.sql
Labels: New Feature

#43 Feat/자동 연동 설정 수정 [PATCH API 엔드포인트 구현]
  .gitignore
  build.gradle
  src/main/java/com/kueennevercry/findex/FindexApplication.java
  src/main/java/com/kueennevercry/findex/controller/AutoSyncConfigController.java
  src/main/java/com/kueennevercry/findex/dto/IndexInfoSummaryDto.java
  src/main/java/com/kueennevercry/findex/dto/request/AutoSyncConfigUpdateRequest.java
  src/main/java/com/kueennevercry/findex/mapper/AutoSyncConfigMapper.java
  src/main/java/com/kueennevercry/findex/service/AutoSyncConfigService.java
  src/main/resources/application.yaml
  src/main/resources/db.yaml
  src/main/resources/http/auto-sync-config-update.http
Labels: Refactor, Test, New Feature

#51 #21 Feature/연동 작업 목록 조회
  build.gradle
  src/main/java/com/kueennevercry/findex/config/QueryDSLConfig.java
  src/main/java/com/kueennevercry/findex/controller/SyncJobController.java
  src/main/java/com/kueennevercry/findex/dto/CursorPageResponseSyncJobDto.java
  src/main/java/com/kueennevercry/findex/dto/SyncJobDto.java
  src/main/java/com/kueennevercry/findex/dto/request/SyncJobParameterRequest.java
  src/main/java/com/kueennevercry/findex/entity/IntegrationTask.java
  src/main/java/com/kueennevercry/findex/mapper/IntegrationTaskMapper.java
  src/main/java/com/kueennevercry/findex/repository/SyncJobCustomRepository.java
  src/main/java/com/kueennevercry/findex/repository/SyncJobCustomRepositoryImpl.java
  src/main/java/com/kueennevercry/findex/repository/SyncJobRepository.java
  src/main/java/com/kueennevercry/findex/service/SyncJobService.java
Labels: New Feature

#46 Feature/지수 성과 랭킹 조회
  src/main/java/com/kueennevercry/findex/controller/IndexDataController.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexDataCreateRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexDataUpdateRequest.java
  src/main/java/com/kueennevercry/findex/entity/IndexData.java
  src/main/java/com/kueennevercry/findex/service/IndexDataService.java
  src/main/java/com/kueennevercry/findex/service/IndexDataServiceImpl.java
Labels: New Feature

#50 Feature/관심 지수 성과 조회
  src/main/java/com/kueennevercry/findex/config/RestTemplateConfig.java
  src/main/java/com/kueennevercry/findex/controller/IndexDataController.java
  src/main/java/com/kueennevercry/findex/repository/IndexDataRepository.java
  src/main/java/com/kueennevercry/findex/repository/IndexInfoRepository.java
  src/main/java/com/kueennevercry/findex/service/IndexDataService.java
  src/main/java/com/kueennevercry/findex/service/IndexDataServiceImpl.java
Labels: New Feature

#58 Feature/지수 데이터 CSV Export
  build.gradle
  src/main/java/com/kueennevercry/findex/controller/IndexDataController.java
  src/main/java/com/kueennevercry/findex/repository/IndexDataRepository.java
  src/main/java/com/kueennevercry/findex/service/IndexDataService.java
  src/main/java/com/kueennevercry/findex/service/IndexDataServiceImpl.java
Labels: New Feature

#59 Feature/자동 연동 설정 목록 조회 [GET API 엔드포인트 구현]
  src/main/java/com/kueennevercry/findex/controller/AutoSyncConfigController.java
  src/main/java/com/kueennevercry/findex/dto/response/AutoSyncConfigDto.java
  src/main/java/com/kueennevercry/findex/dto/response/CursorPageResponse.java
  src/main/java/com/kueennevercry/findex/entity/AutoSyncConfig.java
  src/main/java/com/kueennevercry/findex/mapper/AutoSyncConfigMapper.java
  src/main/java/com/kueennevercry/findex/repository/AutoSyncConfigCustomRepository.java
  src/main/java/com/kueennevercry/findex/repository/AutoSyncConfigCustomRepositoryImpl.java
  src/main/java/com/kueennevercry/findex/repository/AutoSyncConfigRepository.java
  src/main/java/com/kueennevercry/findex/service/AutoSyncConfigService.java
  src/test/resources/http/auto-sync-config-update.http
Labels: New Feature

#60 Feature/지수 정보 연동
  src/main/java/com/kueennevercry/findex/config/OpenApiProperties.java
  src/main/java/com/kueennevercry/findex/controller/SyncJobController.java
  src/main/java/com/kueennevercry/findex/infra/openapi/DefaultOpenApiClient.java
  src/main/java/com/kueennevercry/findex/infra/openapi/IndexInfoApiRequest.java
  src/main/java/com/kueennevercry/findex/infra/openapi/IndexInfoApiResponse.java
  src/main/java/com/kueennevercry/findex/infra/openapi/OpenApiClient.java
  src/main/java/com/kueennevercry/findex/repository/IndexInfoRepository.java
  src/main/java/com/kueennevercry/findex/repository/IntegrationTaskRepository.java
  src/main/java/com/kueennevercry/findex/service/SyncJobService.java
  src/main/resources/application.yaml
Labels: New Feature

#66 refactor: #65 buildUrl 수정
  src/main/java/com/kueennevercry/findex/infra/openapi/DefaultOpenApiClient.java
Labels: Refactor

#69 Fix/프론트 엔드 업데이트
  src/main/resources/static/assets/index-CGZC7fCi.js
  src/main/resources/static/index.html
Labels: Bug fix

#64 Feature/지수 차트 조회
  src/main/java/com/kueennevercry/findex/controller/IndexDataController.java
  src/main/java/com/kueennevercry/findex/dto/ChartDataPoint.java
  src/main/java/com/kueennevercry/findex/repository/IndexDataRepository.java
  src/main/java/com/kueennevercry/findex/repository/SyncJobCustomRepositoryImpl.java
  src/main/java/com/kueennevercry/findex/service/IndexDataService.java
  src/main/java/com/kueennevercry/findex/service/IndexDataServiceImpl.java
  src/test/resources/http/index-data.http
Labels: Refactor, New Feature

#71 fix: 컴파일 오류 수정
  src/main/java/com/kueennevercry/findex/repository/IndexDataRepository.java
  src/main/java/com/kueennevercry/findex/service/IndexDataServiceImpl.java
Labels: Bug fix

#67 refactor/지수 정보 연동 fix
  src/main/java/com/kueennevercry/findex/dto/request/IndexInfoApiRequest.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexInfoApiResponse.java
  src/main/java/com/kueennevercry/findex/infra/openapi/DefaultOpenApiClient.java
  src/main/java/com/kueennevercry/findex/infra/openapi/OpenApiClient.java
  src/main/java/com/kueennevercry/findex/service/SyncJobService.java
Labels: Refactor, Bug fix

#76 Feature/지수 정보 요약 목록 조회 [GET API 구현]
  src/main/java/com/kueennevercry/findex/controller/IndexInfoController.java
  src/main/java/com/kueennevercry/findex/mapper/IndexInfoMapper.java
  src/main/java/com/kueennevercry/findex/repository/IndexInfoRepository.java
  src/main/java/com/kueennevercry/findex/service/IndexInfoService.java
  src/test/resources/http/index-infos.http
Labels: New Feature

#74 Feature/지수 정보 연동 추가기능
  src/main/java/com/kueennevercry/findex/controller/SyncJobController.java
  src/main/java/com/kueennevercry/findex/infra/openapi/DefaultOpenApiClient.java
  src/main/java/com/kueennevercry/findex/service/SyncJobService.java
Labels: Refactor, Bug fix, New Feature

#85 Feature/지수 정보 목록 조회 [GET API 구현] #6
  src/main/java/com/kueennevercry/findex/controller/IndexInfoController.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexInfoListRequest.java
  src/main/java/com/kueennevercry/findex/dto/response/CursorPageResponse.java
  src/main/java/com/kueennevercry/findex/repository/IndexInfoCustomRepository.java
  src/main/java/com/kueennevercry/findex/repository/IndexInfoCustomRepositoryImpl.java
  src/main/java/com/kueennevercry/findex/repository/IndexInfoRepository.java
  src/main/java/com/kueennevercry/findex/service/IndexInfoService.java
  src/test/resources/http/index-infos.http
Labels: New Feature

#89 Fix/지수 데이터 필터 정렬
  src/main/java/com/kueennevercry/findex/mapper/IndexDataMapper.java
  src/main/java/com/kueennevercry/findex/repository/IndexDataCustomRepositoryImpl.java
  src/main/resources/schema.sql
Labels: Bug fix

#95 Fix/지수 정보 목록 조회 #90
  src/main/java/com/kueennevercry/findex/controller/IndexInfoController.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexInfoListRequest.java
  src/main/java/com/kueennevercry/findex/mapper/IndexDataMapper.java
  src/main/java/com/kueennevercry/findex/mapper/IndexInfoMapper.java
  src/main/java/com/kueennevercry/findex/repository/IndexInfoCustomRepositoryImpl.java
  src/main/java/com/kueennevercry/findex/service/IndexInfoService.java
  src/test/resources/http/index-infos.http
Labels: Test, Bug fix

#97 Fix/대시보드 수정
  src/main/java/com/kueennevercry/findex/dto/response/IndexChartDto.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexPerformanceDto.java
  src/main/java/com/kueennevercry/findex/repository/IndexDataRepository.java
  src/main/java/com/kueennevercry/findex/service/IndexDataServiceImpl.java
  src/main/java/com/kueennevercry/findex/service/SyncJobService.java
Labels: Bug fix

#98 Docs/findex v1.0
  src/main/java/com/kueennevercry/findex/config/SwaggerConfig.java
  src/main/java/com/kueennevercry/findex/controller/AutoSyncConfigController.java
  src/main/java/com/kueennevercry/findex/controller/IndexDataController.java
  src/main/java/com/kueennevercry/findex/controller/IndexInfoController.java
  src/main/java/com/kueennevercry/findex/controller/SyncJobController.java
  src/main/java/com/kueennevercry/findex/dto/ChartDataPoint.java
  src/main/java/com/kueennevercry/findex/dto/IndexInfoSummaryDto.java
  src/main/java/com/kueennevercry/findex/dto/PeriodType.java
  src/main/java/com/kueennevercry/findex/dto/SyncJobDto.java
  src/main/java/com/kueennevercry/findex/dto/request/AutoSyncConfigUpdateRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexDataCreateRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexDataSyncRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexDataUpdateRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexInfoApiRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexInfoCreateRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexInfoListRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/IndexInfoUpdateRequest.java
  src/main/java/com/kueennevercry/findex/dto/request/SyncJobParameterRequest.java
  src/main/java/com/kueennevercry/findex/dto/response/AutoSyncConfigDto.java
  src/main/java/com/kueennevercry/findex/dto/response/CursorPageResponse.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexChartDto.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexDataDto.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexInfoApiResponse.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexInfoDto.java
  src/main/java/com/kueennevercry/findex/dto/response/IndexPerformanceDto.java
  src/main/java/com/kueennevercry/findex/dto/response/RankedIndexPerformanceDto.java
Labels: Docs
